const dayjs = require("dayjs");

const HeadlthCheck = [
  {
    id: 1101,
    userId: 1,
    time: [
      {
        year: 2020,
        dateTest: dayjs(new Date(2020, 10, 11, 9, 30)),
        testResult: [
          {
            category: 1,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "ความเข้มข้นของเลือดปกติ ไม่พบภาวะโลหิตจาง",
            // standard is standard value of each section
            // status is  status of value of each section compared to standard
            // 1 is green, 2 is yellow, 3 is red
            result: [
              {
                section: "Hb",
                value: 15.2,
                unit: "g/dL",
                standard: "14.1-18.1 g/dL",
                status: 2,
                icon: "redBlood/hemoglobin.svg",
              },
              {
                section: "Hct",
                value: 44.1,
                unit: "%",
                standard: "43.5-53.7%",
                status: 1,
                icon: "redBlood/hct.svg",
              },
              {
                section: "RBC_Count",
                value: 5.07,
                unit: "mm3L",
                standard: "4.5-6*10^6/mm3",
                status: 3,
                icon: "redBlood/rbc-count.svg",
              },
              {
                section: "RDW",
                value: 12.6,
                unit: "%",
                standard: "9.0-15.0%",
                status: 1,
                icon: "redBlood/rdw.svg",
              },
              {
                section: "RBC_Morph",
                value: "Normal",
                unit: "",
                standard: "Normal/Abnormal",
                status: 2,
                icon: "redBlood/rbc-morph.svg",
              },
              {
                section: "MCV",
                value: 87,
                unit: "fL",
                standard: "80-95 fL",
                status: 1,
                icon: "redBlood/mcv.svg",
              },
              {
                section: "MCH",
                value: 24,
                unit: "pg",
                standard: "27-32 pgL",
                status: 1,
                icon: "redBlood/mch.svg",
              },
              {
                section: "MCHC",
                value: 32.35,
                unit: "g/dL",
                standard: "32-36 g/dL",
                status: 3,
                icon: "redBlood/mchc.svg",
              },
              {
                section: "Plt_Count",
                value: 293,
                unit: "mm3",
                standard: "140-440 10^3/mm3",
                status: 3,
                icon: "redBlood/platelet-count.svg",
              },
              {
                section: "MPV",
                value: 6.0,
                unit: "fL",
                standard: "6.0-12.0 fL",
                status: 1,
                icon: "redBlood/mpv.svg",
              },
            ],
          },
          {
            category: 2,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "จำนวนเม็ดเลือดขาวอยู่ในเกณฑ์ปกติ",
            result: [
              {
                section: "WBC",
                value: 5000,
                unit: "mm3",
                standard: "4000-10000 mm3",
                status: 2,
                icon: "whiteBlood/wbc.svg",
              },
              {
                section: "Netrophil",
                value: 42.5,
                unit: "%",
                standard: "46.5-75%",
                status: 1,
                icon: "whiteBlood/netrophil.svg",
              },
              {
                section: "Neutrophils",
                value: 2422,
                unit: "mm3",
                standard: "2000-7500/mm3",
                status: 3,
                icon: "whiteBlood/netrophils.svg",
              },
              {
                section: "Lymphocyte",
                value: 48.9,
                unit: "%",
                standard: "12-44%",
                status: 1,
                icon: "whiteBlood/lymphocyte.svg",
              },
              {
                section: "Lymphocytes",
                value: 2968,
                unit: "mm3",
                standard: "1500-4000 /mm3",
                status: 2,
                icon: "whiteBlood/lymphocytes.svg",
              },
              {
                section: "Eosinophil",
                value: 3.1,
                unit: "%",
                standard: "0-9.5%",
                status: 1,
                icon: "whiteBlood/eosinophil.svg",
              },
              {
                section: "Eosinophils",
                value: 141,
                unit: "mm3",
                standard: "40-700 /mm3",
                status: 1,
                icon: "whiteBlood/eosinophils.svg",
              },
              {
                section: "Monocyte",
                value: 7.4,
                unit: "%",
                standard: "0-11.2%",
                status: 3,
                icon: "",
              },
              {
                section: "Monocytes",
                value: 449,
                unit: "mm3",
                standard: "200-1000 /mm3",
                status: 3,
                icon: "whiteBlood/monocyte.svg",
              },
              {
                section: "Basophil",
                value: 1.1,
                unit: "%",
                standard: "0-2.5%",
                status: 2,
                icon: "whiteBlood/monocytes.svg",
              },
              {
                section: "Basophils",
                value: 42,
                unit: "mm3",
                standard: "0-200 /mm3",
                status: 2,
                icon: "whiteBlood/basophil.svg",
              },
              {
                section: "Blast",
                value: 1,
                unit: "%",
                standard: "0%",
                status: 2,
                icon: "whiteBlood/blast.svg",
              },
              {
                section: "Blast",
                value: 1,
                unit: "mm3",
                standard: "0 /mm3",
                status: 2,
                icon: "whiteBlood/blastnum.svg",
              },
            ],
          },
          {
            category: 3,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "ระดับน้ำตาลในเลือดปกติ",
            result: [
              {
                section: "FBS",
                value: 99,
                unit: "mg/dL",
                standard: "70-99 mg/dL",
                status: 1,
                icon: "uric_acid/fbs.svg",
              },
            ],
          },
          {
            category: 4,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "ผลการทำงานของไตปกติ",
            result: [
              {
                section: "BUN",
                value: 11,
                unit: "mg/dL",
                standard: "6-20 mg/dL",
                status: 2,
                icon: "kidney/bun.svg",
              },
              {
                section: "Creatinine",
                value: 0.87,
                unit: "mg/dL",
                standard: "0.67-1.17 mg/dL",
                status: 1,
                icon: "kidney/creatinine.svg",
              },
            ],
          },
          {
            category: 5,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "ผลการตรวจเอ็นไซม์การทำงานของตับอยู่ใรเกณฑ์ปกติ",
            result: [
              {
                section: "SGOT",
                value: 41,
                unit: "U/L",
                standard: "0-40 U/L",
                status: 2,
                icon: "liver/sgot.svg",
              },
              {
                section: "SGPT",
                value: 29,
                unit: "U/L",
                standard: "0-41 U/L",
                status: 1,
                icon: "liver/sgpt.svg",
              },
              {
                section: "Alk_Phosphatase",
                value: "NA",
                unit: "U/L",
                standard: "40-130 U/L",
                status: 1,
                icon: "liver/alt-ph.svg",
              },
            ],
          },
          {
            category: 6,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "ผลการตรวจเอ็นไซม์การทำงานของตับอยู่ใรเกณฑ์ปกติ",
            result: [
              {
                section: "Cholesterol",
                value: 201,
                unit: "mg/dL",
                standard: "< 200 mg/dL",
                status: 2,
                icon: "lipid/fat.svg",
              },
              {
                section: "Triglyceride",
                value: 69,
                unit: "mg/dL",
                standard: "< 150 mg/dL",
                status: 1,
                icon: "lipid/triglyceride.svg",
              },
              {
                section: "HDL_Cholesterol",
                value: 76,
                unit: "mg/dL",
                standard: "> 40 mg/dL",
                status: 1,
                icon: "lipid/hdl.svg",
              },
              {
                section: "LDL_Cholesterol",
                value: 111,
                unit: "mg/dL",
                standard: "< 130 mg/dL",
                status: 1,
                icon: "lipid/ldl.svg",
              },
            ],
          },
          {
            category: 7,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: "ผลการตรวจปัสสาวะอยู่ในเกณฑ์ปกติ",
            result: [
              {
                section: "Color",
                value: "Yellow",
                unit: "",
                standard: "Yellow or Pale Yellow",
                status: 1,
                icon: "urine/urine-color.svg",
              },
              {
                section: "Apperance",
                value: "Clear",
                unit: "",
                standard: "Clear, Slightly Turbid",
                status: 2,
                icon: "urine/apperance.svg",
              },
              {
                section: "Sp_Gr",
                value: 1.02,
                unit: "",
                standard: "1.003-1.03",
                status: 3,
                icon: "urine/sp-gr.svg",
              },
              {
                section: "pH",
                value: 7,
                unit: "",
                standard: "4.5-8",
                status: 1,
                icon: "urine/ph.svg",
              },
              {
                section: "WBC",
                value: "0-1",
                unit: "",
                standard: "0-5 cells/HPF",
                status: 2,
                icon: "urine/wbc.svg",
              },
              {
                section: "RBC",
                value: "0-1",
                unit: "",
                standard: "0-5 cells/HPF",
                status: 1,
                icon: "urine/rbc.svg",
              },
              {
                section: "Ertthrocytes",
                value: "Negative",
                unit: "",
                standard: "Negative",
                status: 1,
                icon: "urine/ertthrocytes.svg",
              },
              {
                section: "Glucose",
                value: "Negative",
                unit: "",
                standard: "Negative",
                status: 1,
                icon: "urine/glucose.svg",
              },
              {
                section: "Protein",
                value: "Negative",
                unit: "",
                standard: "Negative",
                status: 1,
                icon: "urine/protein.svg",
              },
              {
                section: "Ketone",
                value: "Negative",
                unit: "",
                standard: "Negative",
                status: 1,
                icon: "urine/ketone.svg",
              },
              {
                section: "Bilirubin",
                value: "Negative",
                unit: "",
                standard: "Negative",
                status: 1,
                icon: "urine/bilirubin.svg",
              },
              {
                section: "Squa_Epi",
                value: "0-1",
                unit: "",
                standard: "0-5 cells/HPF",
                status: 2,
                icon: "urine/squa-epi.svg",
              },
            ],
          },
          {
            category: 8,
            doctor: "ดร.โทนี่ ช็อปเปอร์",
            resultText: " ไม่พบสารเสพติด",
            result: [
              {
                section: "Amphetamine",
                value: "Negative",
                unit: "",
                standard: "Negative",
                status: 1,
                icon: "addictiveSubstance/amphetamine.svg",
              },
            ],
          },
        ],
      },
    ],
  },
];

module.exports = HeadlthCheck;
