const dayjs = require("dayjs");

const HealthData = [
  {
    id: 1001,
    userId: 1,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["พ่อแม่เป็นความดัน"],
      myself: ["-"],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        detail: "ทำแผลหกล้ม",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 1200,
      },
      {
        id: 2,
        category: 2,
        right: 1,
        detail: "ผ่านตัดตับ",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 200000,
      },
      {
        id: 2,
        category: 2,
        right: 2,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 2000,
      },
      {
        id: 2,
        category: 2,
        right: 3,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 1000,
      },
      {
        id: 3,
        category: 2,
        right: 4,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 10000,
      },
      {
        id: 4,
        category: 2,
        right: 5,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 12000,
      },
      {
        id: 5,
        category: 3,
        right: 1,
        detail: "ถอนฝันครุด",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        expess: 3000,
      },
      {
        id: 6,
        category: 1,
        right: 1,
        detail: "รถชน",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 1400,
      },
      {
        id: 6,
        category: 2,
        right: 1,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 200000,
      },
      {
        id: 6,
        category: 2,
        right: 2,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 3000,
      },
      {
        id: 6,
        category: 2,
        right: 3,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 2000,
      },
      {
        id: 7,
        category: 2,
        right: 4,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 15000,
      },
      {
        id: 8,
        category: 2,
        right: 5,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 30000,
      },
      {
        id: 9,
        category: 3,
        right: 1,
        detail: "-",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 2500,
      },
      {
        id: 10,
        category: 1,
        right: 1,
        detail: "โดนต่อย",
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        expess: 800,
      },
    ],
  },
];

module.exports = HealthData;
