const dayjs = require("dayjs");

const HealthData = [
  {
    id: 1001,
    userId: 1,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["พ่อแม่เป็นความดัน"],
      employee: [],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        section: "ทำแผลหกล้ม",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1200,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 1,
        section: "ผ่านตัดตับ",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 2,
        section: "ค่าห้อง + อาหาร (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 3,
        section: "ค่าห้อง ICU (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 3,
        category: 2,
        right: 4,
        section: "ค่าบำบัดโรค",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 10000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 4,
        category: 2,
        right: 5,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 12000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 5,
        category: 3,
        right: 1,
        section: "ถอนฝันครุด",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 1,
        right: 1,
        section: "ปวดหัวเป็นไข้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1400,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 1,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 2,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 3,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 8,
        category: 2,
        right: 4,
        section: "บำบัดจิต",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 15000,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 9,
        category: 2,
        right: 5,
        section: "เสริมคาง",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 30000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 10,
        category: 3,
        right: 1,
        section: "ถอนฟัน",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2500,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: true,
          },
        ],
      },
      {
        id: 11,
        category: 1,
        right: 1,
        section: "ทำแผล",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 800,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
    ],
  },
  {
    id: 1002,
    userId: 2,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["แม่เคยเป็นมะเร็ง "],
      employee: ["เคยขาหักตอนเด็กๆ", ["แขนหักระหว่างทำงาน"]],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        section: "ทำแผลหกล้ม",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1200,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 1,
        section: "ผ่านตัดตับ",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 2,
        section: "ค่าห้อง + อาหาร (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 3,
        section: "ค่าห้อง ICU (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 3,
        category: 2,
        right: 4,
        section: "ค่าบำบัดโรค",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 10000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 4,
        category: 2,
        right: 5,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 12000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 5,
        category: 3,
        right: 1,
        section: "ถอนฝันครุด",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 1,
        right: 1,
        section: "แขนหัก",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1400,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 1,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 2,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 3,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 8,
        category: 2,
        right: 4,
        section: "บำบัดจิต",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 15000,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 9,
        category: 2,
        right: 5,
        section: "เสริมคาง",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 30000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 10,
        category: 3,
        right: 1,
        section: "ถอนฟัน",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2500,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: true,
          },
        ],
      },
      {
        id: 11,
        category: 1,
        right: 1,
        section: "ทำแผล",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 800,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 12,
        category: 2,
        right: 1,
        section: "ไหปล้าร้าแตก",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 800,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
    ],
  },
  {
    id: 1003,
    userId: 3,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["พ่อแม่เป็นความดัน"],
      employee: [],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        section: "ทำแผลหกล้ม",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1200,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 1,
        section: "ผ่านตัดตับ",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 2,
        section: "ค่าห้อง + อาหาร (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 3,
        section: "ค่าห้อง ICU (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 3,
        category: 2,
        right: 4,
        section: "ค่าบำบัดโรค",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 10000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 4,
        category: 2,
        right: 5,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 12000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 5,
        category: 3,
        right: 1,
        section: "ถอนฝันครุด",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 1,
        right: 1,
        section: "ปวดหัวเป็นไข้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1400,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 1,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 2,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 3,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 8,
        category: 2,
        right: 4,
        section: "บำบัดจิต",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 15000,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 9,
        category: 2,
        right: 5,
        section: "เสริมคาง",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 30000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 10,
        category: 3,
        right: 1,
        section: "ถอนฟัน",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2500,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: true,
          },
        ],
      },
      {
        id: 11,
        category: 1,
        right: 1,
        section: "ทำแผล",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 800,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
    ],
  },
  {
    id: 1004,
    userId: 4,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["พ่อแม่เป็นความดัน"],
      employee: [],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        section: "ทำแผลหกล้ม",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1200,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 1,
        section: "ผ่านตัดตับ",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 2,
        section: "ค่าห้อง + อาหาร (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 3,
        section: "ค่าห้อง ICU (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 3,
        category: 2,
        right: 4,
        section: "ค่าบำบัดโรค",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 10000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 4,
        category: 2,
        right: 5,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 12000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 5,
        category: 3,
        right: 1,
        section: "ถอนฝันครุด",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 1,
        right: 1,
        section: "ปวดหัวเป็นไข้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1400,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 1,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 2,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 3,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 8,
        category: 2,
        right: 4,
        section: "บำบัดจิต",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 15000,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 9,
        category: 2,
        right: 5,
        section: "เสริมคาง",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 30000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 10,
        category: 3,
        right: 1,
        section: "ถอนฟัน",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2500,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: true,
          },
        ],
      },
      {
        id: 11,
        category: 1,
        right: 1,
        section: "ทำแผล",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 800,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
    ],
  },
  {
    id: 1005,
    userId: 5,
    birthDate: dayjs(new Date(1995, 10, 1)),
    healthStatus: {
      family: ["พ่อแม่เป็นความดัน"],
      employee: [],
    },
    exercise: [
      {
        date: dayjs(new Date(2021, 8)),
        weight: 76.1,
        height: 172,
        time: 34,
      },
      {
        date: dayjs(new Date(2021, 9)),
        weight: 72.2,
        height: 172,
        time: 32,
      },
      {
        date: dayjs(new Date(2021, 10)),
        weight: 70.4,
        height: 172,
        time: 40,
      },
      {
        date: dayjs(new Date(2021, 11)),
        weight: 67.4,
        height: 172,
        time: 29,
      },
      {
        date: dayjs(new Date(2021, 12)),
        weight: 64.1,
        height: 172,
        time: 33,
      },
    ],
    treatment: [
      {
        id: 1,
        category: 1,
        right: 1,
        section: "ทำแผลหกล้ม",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1200,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 1,
        section: "ผ่านตัดตับ",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 2,
        section: "ค่าห้อง + อาหาร (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 2,
        category: 2,
        right: 3,
        section: "ค่าห้อง ICU (ผ่าตัดตับ)",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 3,
        category: 2,
        right: 4,
        section: "ค่าบำบัดโรค",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 10000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 4,
        category: 2,
        right: 5,
        section: "-",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 12000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 5,
        category: 3,
        right: 1,
        section: "ถอนฝันครุด",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 2,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 6,
        category: 1,
        right: 1,
        section: "ปวดหัวเป็นไข้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 1400,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 1,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 200000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: false,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 2,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 3000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 7,
        category: 2,
        right: 3,
        section: "ผ่าตัดลำไส้",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 8,
        category: 2,
        right: 4,
        section: "บำบัดจิต",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 15000,
        icon: "sick.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 9,
        category: 2,
        right: 5,
        section: "เสริมคาง",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 30000,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
      {
        id: 10,
        category: 3,
        right: 1,
        section: "ถอนฟัน",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 2500,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: true,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: true,
          },
        ],
      },
      {
        id: 11,
        category: 1,
        right: 1,
        section: "ทำแผล",
        type: 1,
        dete: dayjs(new Date(2021, 10, 10)),
        rightUser: 1,
        location: "โรงพยาบาลตัวเอง",
        expenses: 800,
        icon: "surgery.svg",
        note: "-",
        state: [
          {
            id: 1,
            action: "ทำรายการ",
            clear: true,
          },
          {
            id: 1,
            action: "ดำเนินการเอกสาร",
            clear: true,
          },
          {
            id: 3,
            action: "โรงพยาบาลวางบิล",
            clear: true,
          },
          {
            id: 4,
            action: "ประกันโรงพยาบาล",
            clear: false,
          },
          {
            id: 5,
            action: "เสร็จสิ้น",
            clear: false,
          },
        ],
      },
    ],
  },
];

module.exports = HealthData;
