const Insurance = [
  {
    id: 1,
    name: "Syn Mun Kong Insurance",
    protection: "IPD, OPD, อุบัติเหตุ",
    maxCoverage: "150,000 / 200,000 / 300,000 / 400,000 / 500,000",
    medicalExpenses: "รายละเอียดตามแผนประกัน",
    reserve: "No",
    taxDeductible: "Yes",
    highLights: "คุ้มครองสุขภาพและอุบัติเหตุ ส่วนลดค่าเบี้ยประกันตามความฟิต",
    description:
      "ขอเอาใจคนรักสุขภาพกันบ้างนะคะ ด้วยแผนประกันสุขภาพรูปแบบใหม่ ภายใต้แนวคิดการส่งเสริมให้ลูกค้ามีสุขภาพที่แข็งแรง หากคุณออกกำลังกายหรือเดินจนมีจำนวนก้าวครบตามเงื่อนไข คุณก็จะได้รับเบี้ยประกันที่ถูกลง โดยคุ้มครองครอบคลุมทั้งผู้ป่วยในและผู้ป่วยนอก เช่น ค่ารักษาพยาบาลทั่วไป ค่าแพทย์ผ่าตัด ค่าห้อง ICU เป็นต้น ซึ่งมีทั้งหมด 5 แผนให้คุณเลือกได้ตามความต้องการ นอกจากนี้ ยังคุ้มครองในกรณีที่เสียชีวิตจากอุบัติเหตุสูงสุด 500,000 บาทด้วย เหมาะกับผู้ที่ออกกำลังกายเป็นประจำค่ะ",
    rating: 4.5,
    price: 10000,
    site: "https://www-smk-co-th.translate.goog/producthealthdetail/1?_x_tr_sl=th&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=nui,op,sc",
    image: "smk.png",
  },
  {
    id: 2,
    name: "Viriyah Insurance",
    protection: "IPD, อุบัติเหตุ",
    maxCoverage: "100,000 / 300,000 / 700,000",
    medicalExpenses: "จ่ายตามจริง",
    reserve: "Yes",
    taxDeductible: "Yes",
    highLights: "เข้ารักษารพ.ในเครือ BDMS คุ้มครองเหมาจ่าย พร้อมส่วนลด OPD",
    description:
      "สำหรับใครที่ต้องการซื้อประกันสุขภาพเพื่อการรักษาพยาบาลที่เหนือระดับ คุณจะต้องถูกใจแผนประกันนี้อย่างแน่นอน เนื่องจากคุณสามารถเข้ารับการรักษาพยาบาลโดยไม่ต้องสำรองจ่ายจากโรงพยาบาลชั้นนำในเครือ BDMS ทุกที่ทั่วประเทศไทย ซึ่งจะเป็นความคุ้มครองผู้ป่วยในแบบเหมาจ่ายต่อปีสูงสุด 700,000 บาท พร้อมค่าห้องสูงสุด 8,000 บาท/วัน อีกทั้งยังคุ้มครองในส่วนของประกันอุบัติเหตุส่วนบุคคลด้วย และสิทธิประโยชน์สุดพิเศษอีกอย่างหนึ่งก็คือ ส่วนลดค่ารักษาพยาบาลในกรณีผู้ป่วยนอกนั่นเองค่ะ",
    rating: 3.2,
    price: 7000,
    site: "https://www-viriyah-co-th.translate.goog/lp/product/viriyah-healthcare-by-bdms/?_x_tr_sl=th&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=nui,op,sc",
    image: "vry.png",
  },
  {
    id: 3,
    name: "Thai Life Insurance",
    protection: "ชดเชยรายได้",
    maxCoverage: "100,000 / 150,000 / 200,000 / 300,000",
    medicalExpenses: "No",
    reserve: "No",
    taxDeductible: "Yes",
    highLights: "รับเงินชดเชยทั้งเข้าและออกรพ. พร้อมคุ้มครองกรณีเสียชีวิต",
    description:
      "หากคุณเป็นคนหนึ่งที่มักกังวลกับเรื่องการขาดรายได้ขณะเจ็บป่วย เราขอแนะนำประกันสุขภาพแผนนี้เลยค่ะ เพราะคุณจะได้รับความคุ้มครองชดเชยรายได้ขณะนอนโรงพยาบาลทั้งจากการป่วยไข้หรืออุบัติเหตุ โดยจะได้รับเงินชดเชยสูงสุดวันละ 1,500 บาท เป็นระยะเวลาสูงสุด 365 วัน มาพร้อมเงินก้อนเมื่อออกจากโรงพยาบาลสูงสุดครั้งละ 1,500 บาท อีกทั้งยังมีค่าชดเชยกรณีที่คุณเข้ารับการผ่าตัดใหญ่ต่อการเข้าพักรักษาตัวครั้งใดครั้งหนึ่ง นอกจากนี้ ยังให้ความคุ้มครองกรณีเสียชีวิตสูงสุด 300,000 ด้วยนะคะ",
    rating: 4.5,
    price: 5000,
    site: "https://product-thailife-com.translate.goog/%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%81%E0%B8%B1%E0%B8%99%E0%B8%AA%E0%B8%B8%E0%B8%82%E0%B8%A0%E0%B8%B2%E0%B8%9E/%E0%B9%80%E0%B8%95%E0%B8%B4%E0%B8%A1%E0%B9%80%E0%B8%87%E0%B8%B4%E0%B8%99%E0%B8%A2%E0%B8%B2%E0%B8%A1%E0%B8%9B%E0%B9%88%E0%B8%A7%E0%B8%A2?_x_tr_sl=th&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=nui,op,sc",
    image: "tmp.png",
  },
  {
    id: 4,
    name: "FWD",
    protection: "โรคร้ายแรง",
    maxCoverage: "200,000 / 500,000 / 1,000,000",
    medicalExpenses: "No",
    reserve: "No",
    taxDeductible: "Yes",
    highLights: "ตรวจพบมะเร็งทุกชนิด ทุกระยะ รับเงินก้อนสูงสุด 1 ล้านบาท",
    description:
      "มะเร็งถือว่าเป็นโรคร้ายที่ค่ารักษาพยายาบาลนั้นสูงมาก เราจึงขอนำเสนอประกันสำหรับโรคมะเร็งโดยเฉพาะ ซึ่งแผนประกันนี้จะให้ความคุ้มครองโรคมะเร็งทุกชิด ทุกระยะ โดยทางบริษัทจะจ่ายเงินก้อนให้กับคุณเมื่อตรวจพบมะเร็งสูงสุด 1 ล้านบาท เพื่อให้นำไปรักษาตัวในโรงพยาบาลหรือจะนำไปเตรียมความพร้อมสำหรับการต่อสู้กับโรคมะเร็งก็ได้ อีกทั้งยังเป็นความคุ้มครองทันที ซึ่งคุณจะได้รับเล่มกรมธรรม์ภายใน 2 สัปดาห์ นอกจากนี้ คุณยังสามารถนำเบี้ยประกันนี้ไปลดหย่อนภาษีได้ไม่เกิน 15,000 บาทด้วยค่ะ",
    rating: 4.5,
    price: 6000,
    site: "https://ifwd-fwd-co-th.translate.goog/fwd-easy-e-cancer?utm_source=google&utm_medium=cpc&utm_campaign=FWD_TH_EN_CancerInsurance_Search_Google_Brand_BMM&utm_term=%2Bfwd&gclid=CjwKCAiA2O39BRBjEiwApB2IkusPGCtewJrGwSZArbiOUoBY6bh_4vZ-X9AwJRuqN2ZO-laMtS3zehoCIxQQAvD_BwE&_x_tr_sl=th&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=nui,op,sc",
    image: "fwd.png",
  },
  {
    id: 5,
    name: "Cigna",
    protection: "IPD, OPD",
    maxCoverage: "150,000 / 200,000 / 300,000",
    medicalExpenses: "รายละเอียดตามแผนประกัน",
    reserve: "Yes",
    taxDeductible: "No",
    highLights: "กลุ่มโรค Office Syndrome ไม่ต้องสำรองจ่าย ราคาเอื้อมถึงได้",
    description:
      "ด้วยวิถีชีวิตของวัยทำงานในปัจจุบัน คงหนีไม่พ้นกับความเจ็บป่วยจากกลุ่มโรค Office Syndrome ไม่ว่าจะเป็นกระดูกสันหลังเสื่อม, ไมเกรน รวมไปถึงกรดไหลย้อน ซึ่งประกันสุขภาพมิติใหม่นี้จะให้ความคุ้มครองกลุ่มโรคดังกล่าวทั้งผู้ป่วยในและผู้ป่วยนอก อีกทั้งทางบริษัทยังมี Cigna Care Card ที่ทำให้คุณไม่ต้องสำรองจ่ายค่ารักษาพยาบาล ซึ่งขึ้นอยู่กับเงื่อนไขและวงเงินคุ้มครอง โดยมีให้เลือกทั้งหมด 3 แผนตามความต้องการ ส่วนราคาก็เบา ๆ แต่คุ้มครองได้ครบ เรียกได่ว่าคุ้มค่าสุด ๆ ค่ะ",
    rating: 3.9,
    price: 7500,
    site: "https://www-cigna-co-th.translate.goog/our-plans/modern-health-insurance/office-syndrome?utm_source=Affiliate&utm_medium=Interspace&utm_campaign=OfficeSyndrome&_x_tr_sl=th&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=nui%2Cop%2Csc",
    image: "cn.png",
  },
];

module.exports = Insurance;
