const Insurance = [
  {
    id: 1,
    name: "Syn Mun Kong Insurance",
    protection: "IPD, OPD, อุบัติเหตุ",
    maxCoverage: "150,000 / 200,000 / 300,000 / 400,000 / 500,000",
    medicalExpenses: "รายละเอียดตามแผนประกัน",
    reserve: "No",
    taxDeductible: "Yes",
    highLights: "คุ้มครองสุขภาพและอุบัติเหตุ ส่วนลดค่าเบี้ยประกันตามความฟิต",
    description: "",
    rating: 4.5,
    price: 10000,
    profileImage: "tmp.png",
  },
  {
    id: 2,
    name: "Viriyah Insurance",
    protection: "IPD, อุบัติเหตุ",
    maxCoverage: "100,000 / 300,000 / 700,000",
    medicalExpenses: "จ่ายตามจริง",
    reserve: "Yes",
    taxDeductible: "Yes",
    highLights: "เข้ารักษารพ.ในเครือ BDMS คุ้มครองเหมาจ่าย พร้อมส่วนลด OPD",
    description: "",
    rating: 4.2,
    price: 7000,
    profileImage: "tmp.png",
  },
  {
    id: 3,
    name: "Thai Life Insurance",
    protection: "ชดเชยรายได้",
    maxCoverage: "100,000 / 150,000 / 200,000 / 300,000",
    medicalExpenses: "No",
    reserve: "No",
    taxDeductible: "Yes",
    highLights: "รับเงินชดเชยทั้งเข้าและออกรพ. พร้อมคุ้มครองกรณีเสียชีวิต",
    description: "",
    rating: 3.9,
    price: 5000,
    profileImage: "tmp.png",
  },
  {
    id: 4,
    name: "FWD",
    protection: "โรคร้ายแรง",
    maxCoverage: "200,000 / 500,000 / 1,000,000",
    medicalExpenses: "No",
    reserve: "No",
    taxDeductible: "Yes",
    highLights: "ตรวจพบมะเร็งทุกชนิด ทุกระยะ รับเงินก้อนสูงสุด 1 ล้านบาท",
    description: "",
    rating: 3.8,
    price: 6000,
    profileImage: "tmp.png",
  },
  {
    id: 5,
    name: "Cigna",
    protection: "IPD, OPD",
    maxCoverage: "150,000 / 200,000 / 300,000",
    medicalExpenses: "รายละเอียดตามแผนประกัน",
    reserve: "Yes",
    taxDeductible: "No",
    highLights: "กลุ่มโรค Office Syndrome ไม่ต้องสำรองจ่าย ราคาเอื้อมถึงได้",
    description: "",
    rating: 4.9,
    price: 7500,
    profileImage: "tmp.png",
  },
];

module.exports = Insurance;
