const Item = [
  {
    id: 2001,
    name: "iphone 13 pro",
    brand: "Apple",
    type: "LifeStyle",
    quantity: 10,
    category: 6,
    detail:
      "iPhone 13 Pro Max การอัปเกรดระบบกล้องระดับโปรครั้งใหญ่ที่สุดเท่าที่เคยมีมา จอภาพ Super Retina XDR พร้อม ProMotion จึงทั้งเร็วขึ้นและรู้สึกได้ถึงการตอบสนองที่ฉับไวยิ่งขึ้น พร้อมชิป A15 Bionic ที่เร็วสุดขั้ว 5G ที่เร็วสุดแรง แถมยังมีดีไซน์ที่ทนทานและแบตเตอรี่ที่ใช้งานได้ดีที่สุดเท่าที่เคยมีมาใน iPhone อีกด้วย",
    rating: 4.5,
    price: 7000,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1234,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
  {
    id: 2002,
    name: "Iphone 13",
    brand: "Apple",
    type: "LifeStyle",
    quantity: 10,
    category: 6,
    detail:
      "iPhone 13 ระบบกล้องคู่ที่ล้ำหน้าที่สุดเท่าที่เคยมีมาบน iPhone พร้อมชิป A15 Bionic ที่เร็วสุดขั้ว, แบตเตอรี่ที่ใช้งานได้นานขึ้น แบบก้าวกระโดดครั้งใหญ่, ดีไซน์ที่ทนทาน, 5G ที่เร็วสุดแรง1 และจอภาพ Super Retina XDR ที่สว่างยิ่งขึ้น",
    rating: 4.2,
    price: 6000,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1235,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
  {
    id: 2003,
    name: "MacBook Pro",
    brand: "Apple",
    type: "LifeStyle",
    quantity: 10,
    category: 1,
    detail:
      "MacBook Pro ที่ทรงพลังยิ่งกว่าครั้งไหนๆ มาถึงแล้ว ด้วยชิป M1 Pro หรือ M1 Max ที่เร็วสุดขั้ว และยังเป็น Apple Silicon ตัวแรกที่ออกแบบมาสำหรับมือโปร เพื่อให้คุณได้สัมผัสกับประสิทธิภาพการทำงานสุดล้ำและแบตเตอรี่ที่ใช้งานได้นานอย่างยอดเยี่ยม ยิ่งไปกว่านั้นยังมีจอภาพ Liquid R200etina XDR ที่สวยงามน่าทึ่ง พร้อมด้วยกล้องและระบบเสียงที่ดีที่สุดเท่าที่เคยมีมาในโน้ตบุ๊ก Mac และยังมีครบทุกพอร์ตที่คุณต้องการด้วย เรียกว่าเป็นครั้งแรกในโน้ตบุ๊กระดับเดียวกัน ซึ่งบอกเลยว่า MacBook Pro เครื่องนี้คือเหลือร้ายเลยล่ะ",
    rating: 3.8,
    price: 12000,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1236,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
  {
    id: 2004,
    name: "MacBook Air",
    brand: "Apple",
    type: "LifeStyle",
    quantity: 10,
    category: 1,
    detail:
      "โน้ตบุ๊กที่บางและเบาที่สุดของเรา วันนี้พลิกโฉมใหม่หมดในทุกด้าน ด้วยชิป Apple M1 ที่ทำให้มี CPU เร็วขึ้นสูงสุด 3.5 เท่า และ GPUเร็วขึ้นสูงสุด 5 เท่า รวมทั้ง Neural Engine ที่ล้ำหน้าที่สุดของเรา ซึ่งเสริมให้การเรียนรู้ของระบบเร็วขึ้นสูงสุดถึง 9 เท่า พร้อมด้วยแบตเตอรี่ที่ใช้งานได้นานที่สุดเท่าที่เคยมีมาใน MacBook Air ซึ่ง    ครั้งนี้มาในดีไซน์แบบไม่มีพัดลมที่มีก็แต่ความเงียบ เอาเป็นว่า ไม่เคยมีครั้งไหนที่พลังระดับนี้จะพร้อมไปกับคุณได้เท่านี้มาก่อน",
    rating: 4.5,
    price: 7000,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1237,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
  {
    id: 2005,
    name: "Apple Watch Series 7",
    brand: "Apple",
    type: "LifeStyle",
    quantity: 10,
    category: 1,
    detail:
      "Apple Watch Series 7 มาพร้อมระบบเซลลูลาร์ที่ช่วยให้คุณต่อติดกับคนรอบตัวและข้อมูลที่คุณใส่ใจได้เสมอ แม้ว่าคุณจะไม่มี iPhone อยู่กับตัวก็ตาม รับสายและตอบข้อความ สตรีมเพลงและพ็อดคาสท์ที่คุณชอบ นอกจากนี้ คุณรับความช่วยเหลือได้อย่างรวดเร็วด้วย SOS ฉุกเฉิน และยังโทรฉุกเฉินทั่วโลกได้อีกด้วย",
    rating: 4.5,
    price: 4000,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1238,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
  {
    id: 2005,
    name: "Uniqlo AIRism",
    brand: "Uniqlo",
    type: "LifeStyle",
    quantity: 10,
    category: 2,
    detail:
      "สวมใส่สบายอย่างเหนือชั้นเพื่อให้คุณไม่รู้สึกอับชื้น ชุดชั้นในสวมใส่สบายในทุกวัน",
    rating: 4.2,
    price: 100,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1239,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
  {
    id: 2006,
    name: "Sony WH-1000XM4",
    brand: "Sony",
    type: "LifeStyle",
    quantity: 10,
    category: 3,
    detail:
      "หูฟังอันชาญฉลาดและใช้งานง่าย WH-1000XM4 ผ่านการปรับปรุงระดับการตัดเสียงรบกวนที่ดีที่สุดในระดับแนวหน้าของอุตสาหกรรม ให้คุณภาพเสียงที่ยอดเยี่ยม และการสั่งงานอัจฉริยะที่ปรับเปลี่ยนตามพฤติกรรมและพิกัดสถานที่ของคุณ",
    rating: 3.9,
    price: 4000,
    discount: 0,
    count: 1000,
    image: "/item/tmp.png",
    skuCode: 1232,
    warranty: 2,
    warrantyDetail: "รับปรกันในด้านความผิดปกติในการใช้งานจากการผลิตเท่านั้น",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
  },
];

module.exports = Item;
