const Item = [
  {
    id: 2001,
    name: "Iphone 12 pro",
    quantity: 20,
    detail:
      "A14 Bionic ที่แรงแซงหน้าชิพในบรรดาสมาร์ทโฟนอื่นๆ ไปไกลหลายขุม ระบบกล้องระดับโปรที่ยกระดับการถ่ายภาพใน สภาวะแสงน้อยไปอีกขั้น รวมทั้ง Ceramic Shield ที่ทนต่อการตกกระแทกได้ดีขึ้น 4 เท่า",
    category: 6,
    price: 8000,
    discount: 10,
    newPrice: 7200,
    brand: "Apple",
    skuCode: 2001001,
    warranty: 1,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 20,
    image: [
      "/item/iphone12Pro_model.png",
      "/item/iphone12Pro_color.png",
      "/item/iphone12Pro_detail.png",
    ],
    type: "lifestyle",
    count: 500,
  },
  {
    id: 2002,
    name: "PlayStation Pro",
    quantity: 30,
    detail:
      "Sony PlayStation Pro ความจุ 2TB ตัวเครื่องแสดงผลภาพระดับ 4K/60 Fps รองรับระบบ HDR ให้ความคมชัดของภาพกราฟิก ให้นักเกมเมอร์ได้สัมผัสกับเกมได้สนุกยิ่งขึ้น",
    category: 3,
    price: 4000,
    discount: 5,
    newPrice: 3800,
    brand: "Sony",
    skuCode: 2001002,
    warranty: 1,
    warrantyDetail: "รับประกันความผิดปกติของสินค้าที่เกิดจากการผลิต",
    deliveryType: 1,
    deliveryTime: 3,
    deliveryCost: 30,
    image: ["/item/ps5Box.png", "/item/ps5Model.png", "/item/ps5Joy.png"],
    type: "lifestyle",
    count: 1000,
  },
];

module.exports = Item;
