export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAIL = "CART_FAIL";

export const USERS_FETCHING = "USERS_FETCHING";
export const USERS_FAILED = "USERS_FAILED";
export const USERS_SUCCESS = "USERS_SUCCESS";

export const USERPROFILE_FETCHING = "USERPROFILE_FETCHING";
export const USERPROFILE_FAILED = "USERPROFILE_FAILED";
export const USERPROFILE_SUCCESS = "USERPROFILE_SUCCESS";

export const COURSE_FETCHING = "COURSE_FETCHING";
export const COURSE_FAILED = "COURSE_FAILED";
export const COURSE_SUCCESS = "COURSE_SUCCESS";

export const DEPARTMENT_FETCHING = "DEPARTMENT_FETCHING";
export const DEPARTMENT_FAILED = "DEPARTMENT_FAILED";
export const DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";

export const COURSEITEM_FETCHING = "COURSEITEM_FETCHING";
export const COURSEITEM_FAILED = "COURSEITEM_FAILED";
export const COURSEITEM_SUCCESS = "COURSEITEM_SUCCESS";

export const INSURANCE_FETCHING = "INSURANCE_FETCHING";
export const INSURANCE_FAILED = "INSURANCE_FAILED";
export const INSURANCE_SUCCESS = "INSURANCE_SUCCESS";

export const ITEM_FETCHING = "ITEM_FETCHING";
export const ITEM_FAILED = "ITEM_FAILED";
export const ITEM_SUCCESS = "ITEM_SUCCESS";

export const SHOPCATEGORY_FETCHING = "SHOPCATEGORY_FETCHING";
export const SHOPCATEGORY_FAILED = "SHOPCATEGORY_FAILED";
export const SHOPCATEGORY_SUCCESS = "SHOPCATEGORY_SUCCESS";

export const TRAVELCATEGORY_FETCHING = "TRAVELCATEGORY_FETCHING";
export const TRAVELCATEGORY_FAILED = "TRAVELCATEGORY_FAILED";
export const TRAVELCATEGORY_SUCCESS = "TRAVELCATEGORY_SUCCESS";

export const TRAVEL_FETCHING = "TRAVEL_FETCHING";
export const TRAVEL_FAILED = "TRAVEL_FAILED";
export const TRAVEL_SUCCESS = "TRAVEL_SUCCESS";

export const DETAIL_FETCHING = "DETAIL_FETCHING";
export const DETAIL_FAILED = "DETAIL_FAILED";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";

export const MAINCATEGORY_FETCHING = "MAINCATEGORY_FETCHING";
export const MAINCATEGORY_FAILED = "MAINCATEGORY_FAILED";
export const MAINCATEGORY_SUCCESS = "MAINCATEGORY_SUCCESS";

export const PACKAGE_FETCHING = "PACKAGE_FETCHING";
export const PACKAGE_FAILED = "PACKAGE_FAILED";
export const PACKAGE_SUCCESS = "PACKAGE_SUCCESS";

export const HISTORY_FETCHING = "HISTORY_FETCHING";
export const HISTORY_FAILED = "HISTORY_FAILED";
export const HISTORY_SUCCESS = "HISTORY_SUCCESS";
