export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAIL = "CART_FAIL";

export const USERS_FETCHING = "USERS_FETCHING";
export const USERS_FAILED = "USERS_FAILED";
export const USERS_SUCCESS = "USERS_SUCCESS";

export const USERPROFILE_FETCHING = "USERPROFILE_FETCHING";
export const USERPROFILE_FAILED = "USERPROFILE_FAILED";
export const USERPROFILE_SUCCESS = "USERPROFILE_SUCCESS";

export const COURSE_FETCHING = "COURSE_FETCHING";
export const COURSE_FAILED = "COURSE_FAILED";
export const COURSE_SUCCESS = "COURSE_SUCCESS";

export const DEPARTMENT_FETCHING = "DEPARTMENT_FETCHING";
export const DEPARTMENT_FAILED = "DEPARTMENT_FAILED";
export const DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";

export const COURSEITEM_FETCHING = "COURSEITEM_FETCHING";
export const COURSEITEM_FAILED = "COURSEITEM_FAILED";
export const COURSEITEM_SUCCESS = "COURSEITEM_SUCCESS";

export const INSURANCE_FETCHING = "INSURANCE_FETCHING";
export const INSURANCE_FAILED = "INSURANCE_FAILED";
export const INSURANCE_SUCCESS = "INSURANCE_SUCCESS";

export const INSURANCECATEGORY_FETCHING = "INSURANCECATEGORY_FETCHING";
export const INSURANCECATEGORY_FAILED = "INSURANCECATEGORY_FAILED";
export const INSURANCECATEGORY_SUCCESS = "INSURANCECATEGORY_SUCCESS";

export const ITEM_FETCHING = "ITEM_FETCHING";
export const ITEM_FAILED = "ITEM_FAILED";
export const ITEM_SUCCESS = "ITEM_SUCCESS";

export const SHOPCATEGORY_FETCHING = "SHOPCATEGORY_FETCHING";
export const SHOPCATEGORY_FAILED = "SHOPCATEGORY_FAILED";
export const SHOPCATEGORY_SUCCESS = "SHOPCATEGORY_SUCCESS";

export const TRAVELCATEGORY_FETCHING = "TRAVELCATEGORY_FETCHING";
export const TRAVELCATEGORY_FAILED = "TRAVELCATEGORY_FAILED";
export const TRAVELCATEGORY_SUCCESS = "TRAVELCATEGORY_SUCCESS";

export const TRAVEL_FETCHING = "TRAVEL_FETCHING";
export const TRAVEL_FAILED = "TRAVEL_FAILED";
export const TRAVEL_SUCCESS = "TRAVEL_SUCCESS";

export const DETAIL_FETCHING = "DETAIL_FETCHING";
export const DETAIL_FAILED = "DETAIL_FAILED";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";

export const MAINCATEGORY_FETCHING = "MAINCATEGORY_FETCHING";
export const MAINCATEGORY_FAILED = "MAINCATEGORY_FAILED";
export const MAINCATEGORY_SUCCESS = "MAINCATEGORY_SUCCESS";

export const PACKAGE_FETCHING = "PACKAGE_FETCHING";
export const PACKAGE_FAILED = "PACKAGE_FAILED";
export const PACKAGE_SUCCESS = "PACKAGE_SUCCESS";

export const DELIVERY_FETCHING = "DELIVERY_FETCHING";
export const DELIVERY_FAILED = "DELIVERY_FAILED";
export const DELIVERY_SUCCESS = "DELIVERY_SUCCESS";

export const FACILITIES_FETCHING = "FACILITIES_FETCHING";
export const FACILITIES_FAILED = "FACILITIES_FAILED";
export const FACILITIES_SUCCESS = "FACILITIES_SUCCESS";

export const HISTORY_FETCHING = "HISTORY_FETCHING";
export const HISTORY_FAILED = "HISTORY_FAILED";
export const HISTORY_SUCCESS = "HISTORY_SUCCESS";

export const HEALTH_FETCHING = "HEALTH_FETCHING";
export const HEALTH_FAILED = "HEALTH_FAILED";
export const HEALTH_SUCCESS = "HEALTH_SUCCESS";

export const NOTIFICATION_FETCHING = "NOTIFICATION_FETCHING";
export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";

export const RIGHTTREATMENT_FETCHING = "RIGHTTREATMENT_FETCHING";
export const RIGHTTREATMENT_FAILED = "RIGHTTREATMENT_FAILED";
export const RIGHTTREATMENT_SUCCESS = "RIGHTTREATMENT_SUCCESS";

export const HEALTHCHECK_FETCHING = "HEALTHCHECK_FETCHING";
export const HEALTHCHECK_FAILED = "HEALTHCHECK_FAILED";
export const HEALTHCHECK_SUCCESS = "HEALTHCHECK_SUCCESS";

export const HEALTHCHECKCATEGORY_FETCHING = "HEALTHCHECKCATEGORY_FETCHING";
export const HEALTHCHECKCATEGORY_FAILED = "HEALTHCHECKCATEGORY_FAILED";
export const HEALTHCHECKCATEGORY_SUCCESS = "HEALTHCHECKCATEGORY_SUCCESS";

export const TREATMENTCATEGORY_FETCHING = "TREATMENTCATEGORY_FETCHING";
export const TREATMENTCATEGORY_FAILED = "TREATMENTCATEGORY_FAILED";
export const TREATMENTCATEGORY_SUCCESS = "TREATMENTCATEGORY_SUCCESS";

export const BILL_FETCHING = "BILL_FETCHING";
export const BILL_FAILED = "BILL_FAILED";
export const BILL_SUCCESS = "BILL_SUCCESS";

export const HOSPITAL_FETCHING = "HOSPITAL_FETCHING";
export const HOSPITAL_FAILED = "HOSPITAL_FAILED";
export const HOSPITAL_SUCCESS = "HOSPITAL_SUCCESS";
